name: dart_udx
description: A Dart implementation of UDX - reliable, multiplexed, and congestion-controlled streams over UDP
version: 0.3.0
homepage: https://github.com/yourusername/udx

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.3
  mockito: ^5.4.4
  collection: ^1.18.0
  meta: ^1.16.0
dev_dependencies:
  build_runner: ^2.4.9
  lints: ^3.0.0
  test: ^1.24.0
  mockito: ^5.4.4
